.TH TAQUIN 1 2016-04-15 taquin
.SH NAME
taquin \- run a solver of N-Puzzle's board!
.SH SYNOPSIS
.B taquin
\fI \fR[\fIOPTIONS\fR...]
.SH DESCRIPTION
.B taquin
Taquin (N-Puzzle) is a sliding puzzle that consists of a frame of numbered square tiles in random order with one tile missing.
.SH OPTIONS
.TP
\fB\-show\fresolve board with intermediate information of resolution.
.SH AUTHOR
Written by lecorref <lecorref@users.noreply.github.com> and adjivas <adjivas@users.noreply.github.com>.
