.TH TAQUIN 1 2016-04-15 taquin
.SH NAME
taquin \- run a solver of N-Puzzle's board!
.SH SYNOPSIS
.B npuzzle
\fI \fR[\fIOPTIONS\fR...]
.SH DESCRIPTION
.B npuzzle
Taquin (N-Puzzle) is a sliding puzzle that consists of a frame of numbered square tiles in random order with one tile missing.
.SH OPTIONS
.TP
\fB\-h\fr, \fB\--heuristic\fr Resolve a board with specific heuristic, take in argument manhattan, conflicts, linear-conflict, misplaced-tiles or n-maxswap.
.TP
\fB\-s\fr, \fB\--show\fr Resolve board with intermediate information of resolution.
.TP
\fB\-l\fr, \fB\--load\fr Add input's boards.
.TP
\fB\-b\fr, \fB\--goal\fr Add goal's board.

.SH AUTHOR
Written by lecorref <lecorref@users.noreply.github.com> and adjivas <adjivas@users.noreply.github.com>.
